### ISSUE TITLE
Release 1.0.4?

### ISSUE THREAD

**Issue by sideshowbarker** [shapesecurity/salvation#100]
It’d be great to have a new Salvation release (1.0.4?) if y’all are now at a point where you can do one.

I’d like to do a new [W3C Nu HTML Checker](https://github.com/validator/validator) release/update relatively soon, but am holding off until it can include the Salvation [“support future directives”](https://github.com/shapesecurity/salvation/commit/1d9c70c6dace8caef6d1cfa9cd6bf40919d2e0d9), [`sandbox` directive warnings](https://github.com/shapesecurity/salvation/commit/2014f9795a2a32636cd8c35dd002490e5ea655b4) & [GH-93 branch](https://github.com/shapesecurity/salvation/commit/489185b585597ce7f1fd1cefcbc7402e9b3340a9) changes.

**Comment by michaelficarra** [comment]
We plan to do #98 and #99 in the next few days, then we'll release 2.0.0. I'll try to also make a tiny migration guide to help with the backward incompatibilities introduced by #93 and #99.

**Comment by sideshowbarker** [comment]
Sounds great—I’ll wait for it

**Comment by michaelficarra** [comment]
@sideshowbarker Released 2.0.0. Enjoy!

**Comment by sideshowbarker** [comment]
Rock-n-roll! :smile: Thanks much—will try to get this deployed to the W3C validator today
