### ISSUE TITLE
warn on duplicate declarations

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/salvation#112]
`script-src a b; script-src b c` should produce a duplicate declaration warning, even though we have given it intersectional merge semantics (matching common implementation behaviour).

From [the spec](https://www.w3.org/TR/CSP2/#policy-parsing):

> If the set of directives already contains a directive whose name is a case insensitive match for directive name, ignore this instance of the directive and continue to the next token.

**Comment by shekyan** [comment]
@michaelficarra , I couldn't recall why we made the decision to do intersect merge on duplicate directives, so I verified:
FF says `Content Security Policy: Duplicate script-src directives detected.  All but the first instance will be ignored.`
Chrome's message could've been bettter, as it actually drops all but first too and says `Ignoring duplicate Content-Security-Policy directive 'script-src'`. So I guess we should follow the spec.
