### ISSUE TITLE
Policy intersection and union should be case insensitive.

### ISSUE THREAD

**Issue by ilyanesterov** [shapesecurity/salvation#120]
intersect:
```java
Policy p = parse("default-src 'self' example.com; ");
Policy q = parse("default-src 'self' EXAMPLE.COM; ");
p.intersect(q);
```
will result following policy ` default-src 'self'` instead of `default-src 'self' example.com;` or `default-src 'self' EXAMPLE.COM;`

in case of union:
```java
Policy p = parse("default-src 'self' example.com; ");
Policy q = parse("default-src 'self' EXAMPLE.COM; ");
p.union(q);
```
result is the `default-src 'self' example.com EXAMPLE.COM` but it should be `default-src 'self' example.com;` or `default-src 'self' EXAMPLE.COM;`

I'm not sure about lowercase vs UPPERCASE or even vs CaMeLcAsE in result of intersect or union, but I would just leave it in lowercase.

**Comment by michaelficarra** [comment]
Confirmed. I think we'll just end up lower-casing the scheme, host, and path when a HostSource is constructed since they're all insignificant when matching.

**Comment by shekyan** [comment]
@michaelficarra , just scheme and host. `path-part` matching is case-sensitive :point_up: . We can just do case insensitive comparison of scheme and host. Check out https://github.com/shapesecurity/salvation/pull/122

**Comment by michaelficarra** [comment]
@shekyan See step [11.4.3](https://www.w3.org/TR/CSP2/#match-source-expression) as well as [our implementation](https://github.com/shapesecurity/salvation/blob/98df95db5a3b813e935c9db7a7ab2f956ec36b97/src/main/java/com/shapesecurity/salvation/directiveValues/HostSource.java#L84) which both do a case insensitive comparison of path.

**Comment by shekyan** [comment]
What is 4.11.4.3? Anyway, both  FF and Chrome implement case sensitive:
```
package main

import (
    "fmt"
    "net/http"
)

func main() {
    http.HandleFunc("/script", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintln(w, `
    alert(1);
  `)
    })

    http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        w.Header().Set("Content-Security-Policy", "script-src localhost:8888/SCRIPT;")
    fmt.Fprintln(w, `<html>
    <body>
      <button">Go</button>
      <script src='/script'></script>
    </body>
  </html>`)
    })
    http.ListenAndServe(":8888", nil)
}

```

**Comment by michaelficarra** [comment]
Then we should wait to fix this until they fix their implementations. Care to open some bug reports?

**Comment by shekyan** [comment]
trying.

**Comment by shekyan** [comment]
Reported [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1251908), [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=590502) and a security bug for Chromium. #122 addresses case-sensitivity issues around scheme-part and host-part and keeps existing behavior for path-part. I suggest opening another issue to track path-matching and merge this.

**Comment by ilyanesterov** [comment]
Great! Thanks @shekyan

**Comment by shekyan** [comment]
[This commit](https://github.com/w3c/webappsec-csp/commit/dbeca439ccca4d99ccb34f0ef09570ce6a498bd5) defines path-part be case-sensitive match. I'll update PR to reflect spec changes.
