### ISSUE TITLE
Handle `source-expression`s that contain both 'unsafe-inline' and hash/nonce

### ISSUE THREAD

**Issue by shekyan** [shapesecurity/salvation#130]
Remove "'usanfe-inline'" if `source-list` contains both "'usanfe-inline'" and hash-source/nonce-source

**Comment by michaelficarra** [comment]
I don't understand this. Are they not allowed to coexist?

**Comment by shekyan** [comment]
Nop. I'll add an explicit note to the spec, meanwhile 
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'nonce-123'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

```

**Comment by michaelficarra** [comment]
That's really strange. I still don't get why they can't exist simultaneously.

**Comment by shekyan** [comment]
What would mean "'unsafe-inline'" and hash/nonce coexisting together? Subset of inline resources that satisfies both "'unsafe-inline'" and hash/source would be the same subset that satisfies only hash/nonce, which imply that "'unsafe-inline'" has no effect if nonce/hash is present.

There is another change that would shock you:) Presence of  `unsafe-dynamic` invalidates "'unsafe-inline'", `hash-source` and 'nonce-source'!

**Comment by michaelficarra** [comment]
As we discussed offline, we'll just add a warning when both are present, as this is essentially equivalent to `'none'` (not `'unsafe-inline'` as one might expect).

**Comment by shekyan** [comment]
Added warning generation. I'll be happy to de-dup actual warning message if you have in mind where to put it.
