### ISSUE TITLE
Policy.show() doesnt handle 'none' correctly?

### ISSUE THREAD

**Issue by psiinon** [shapesecurity/salvation#148]
As per your example:
`Origin origin = URI.parse("http://example.com");`
`Policy p = new Policy(origin);`
`Set<SourceExpression> scriptSourceValues = new HashSet<>();`
`scriptSourceValues.add(None.INSTANCE);`
`p.addDirective(new ScriptSrcDirective(scriptSourceValues));`
`System.out.println("Policy = " + p.show());`
Gives:
`Policy = script-src`
Shouldnt it report:
`Policy = script-src: 'none'`
Or am I misunderstanding how this should work?

**Comment by michaelficarra** [comment]
Those policies are functionally identical. Salvation is smart enough to optimise policies and to use the smallest rendering in most cases.

**Comment by psiinon** [comment]
Ok, thanks for letting me know.
