### ISSUE TITLE
Which Merge Addresses Multiple Policies (Headers)?

### ISSUE THREAD

**Issue by kingthorin** [shapesecurity/salvation#149]
Is it [union merge](https://github.com/shapesecurity/salvation#manipulate-policies) that is meant to address: https://www.w3.org/TR/CSP2/#enforcing-multiple-policies ?

BTW just so you're in the loop I'm working on leveraging Salvation to analyze CSP via ZAP, https://github.com/zaproxy/zaproxy/issues/527

**Comment by shekyan** [comment]
@kingthorin nop, that would be the intersection merge.

BTW, it is awesome that you guys working on it. We were thinking of integrating Salvation with ZAP very long time ago;)  Will be happy to help with it.

**Comment by kingthorin** [comment]
Thanks. Feel free to close this ticket.
