### ISSUE TITLE
add support for 'unsafe-hashed-attributes' source expression

### ISSUE THREAD

**Issue by ilyanesterov** [shapesecurity/salvation#150]
https://www.w3.org/TR/CSP3/#grammardef-keyword-source

**Comment by shekyan** [comment]
AFAIK it's gonna be removed from the spec because syntax it is not backwards compatible with browsers that don't support it. But let's keep this issue open until things get clearer.

**Comment by shekyan** [comment]
Closed in https://github.com/shapesecurity/salvation/pull/179
