### ISSUE TITLE
Policy doesn't implement allows checks for all source directives

### ISSUE THREAD

**Issue by kingthorin** [shapesecurity/salvation#151]
[Policy.java](https://github.com/shapesecurity/salvation/blob/master/src/main/java/com/shapesecurity/salvation/data/Policy.java) needs allows checks added for font, media, object, default, etc [directives](https://github.com/shapesecurity/salvation/tree/master/src/main/java/com/shapesecurity/salvation/directives).

Or were those purposefully excluded?

**Comment by shekyan** [comment]
We didn't have immediate need for those checks, so we prioritized implementing them low. 
I'll try to implement them soon.

**Comment by kingthorin** [comment]
Do you accept pull requests? I could probably knock that together later this weekend.

**Comment by shekyan** [comment]
Of course!
