### ISSUE TITLE
Remove warning about 'referrer' directive

### ISSUE THREAD

**Issue by ilyanesterov** [shapesecurity/salvation#173]
If CSP contains `referrer` directive, salvation gives a warning about usage of it: `The referrer directive is an experimental directive that will be likely added to the CSP specification.` . However `referrer` directive has been removed from CSP in favor of referrer policy https://w3c.github.io/webappsec-referrer-policy/

**Comment by michaelficarra** [comment]
So we should make it more like a deprecation message instead?

> The referrer directive was an experimental directive that was proposed but never added to the CSP specification. Support for this directive will be removed. Instead, use the Referrer-Policy HTTP header.

**Comment by shekyan** [comment]
To be precise, delivery mechanism is not only HTTP header, but those listed in https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery. 
So to rephrase you message:
> The referrer directive was an experimental directive that was proposed but never added to the CSP specification. Support for this directive will be removed. Instead, use delivery mechanisms defined in the <a href="https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery">referrer policy delivery</a> section of the specification.

**Comment by ilyanesterov** [comment]
Just to add some data points: Chrome 56 will remove support for it https://bugs.chromium.org/p/chromium/issues/detail?id=658761 . Firefox should do the same pretty soon: https://bugzilla.mozilla.org/show_bug.cgi?id=1302449

So we need to warn users that they shouldn't use it.
