### ISSUE TITLE
Feature request: Add CSP version compatibility flag

### ISSUE THREAD

**Issue by ilyanesterov** [shapesecurity/salvation#175]
That would be nice to have a compatibility flag to evaluate given CSP policy against given version, e.g. CSPv1, CSPv2, CSPv3. The reason is that the same policy will look different for different browsers depends on which version of CSP spec they currently support.

**Comment by michaelficarra** [comment]
The web is not versioned, and Salvation will only support the web intersection semantics. For legacy CSP support, an old version of Salvation may be used.
