### ISSUE TITLE
Wrong validation of HashSource

### ISSUE THREAD

**Issue by cnsgithub** [shapesecurity/salvation#202]
**What is the problem?**
Generating a SHA-256 hash - I didn't test the other algorithms - with salvation 2.5.0 and checking with https://cspvalidator.org fails.

**How to reproduce?**
1. Generate `script-src `directive containing SHA-256 hash:

```java
		Origin origin = URI.parse("http://localhost");
		Policy policy = new Policy(origin);
		policy.addDirective(new ScriptSrcDirective(Collections.singleton(new HashSource(HashSource.HashAlgorithm.SHA256, new Base64Value(Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest("function foo() { bla('123'); }".getBytes(/*StandardCharsets.US_ASCII*/))))))));
		System.out.println(policy.show());

```
 Return value: `script-src 'sha256-YWFmMzU3YWU0ZDYzM2IzYWEzZTIzOTg2Yjk1ZGFjYWQ2YzgyZDdhZDM4MTAyZWUwMjNmZjk5M2IwNWUzN2RkOA=='`

2. Test it with [cspvalidator](https://cspvalidator.org/#headerValue%5B%5D=script-src+'sha256-YWFmMzU3YWU0ZDYzM2IzYWEzZTIzOTg2Yjk1ZGFjYWQ2YzgyZDdhZDM4MTAyZWUwMjNmZjk5M2IwNWUzN2RkOA%3D%3D'&strategy=intersection):

![image](https://user-images.githubusercontent.com/13161711/43185117-3ef79a06-8feb-11e8-8474-f17a4667f380.png)

**Comment by cnsgithub** [comment]
I changed the title of this issue because further investigation revealed a bug in `HashSource.validationErrors` or `Base64.size` respectively. So, this is not related to generation, but to validation.

In `HashSource.validationErrors` you probably wanted to check the length of the hashes. But what you are actually doing is to check the length of the decoded `Base64Value`.

Furthermore the length of SHA-256 hashes should be 64 instead of 32 and so on:
```java
	public void validationErrors() {
		switch (this.algorithm) {
			case SHA256:
				if (this.value.size() != 32) {
					throw new IllegalArgumentException("Invalid SHA-256 value (wrong length): " + this.value.size() + ".");
				}
				break;
...
```

**Comment by cnsgithub** [comment]
PR: https://github.com/shapesecurity/salvation/pull/203

**Comment by cnsgithub** [comment]
Hmm, I am also confused now since all sources I tested generate the same SHA-256 hash. :confused: 

This is what [W3C](https://w3c.github.io/webappsec-csp/#unsafe-hashes-usage) has:
`doSubmit() => sha256-jzgBGA4UWFFmpOBq0JpdsySukE1FrEN5bUpoK8Z29fY=`

This matches absolutely with [Report URI](https://report-uri.com/home/hash):
![image](https://user-images.githubusercontent.com/13161711/43504231-e0d3d8ae-9562-11e8-923f-3873c0d8cbfb.png)

And with [online-convert.com](https://hash.online-convert.com/sha256-generator):
![image](https://user-images.githubusercontent.com/13161711/43504273-0ada93b8-9563-11e8-9fb5-d1d53298552d.png)

I think the way I am generating my hashes must be wrong. :crying_cat_face: 

But wait, what I am actually doing - `Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest("doSubmit()".getBytes()))` - also returns `jzgBGA4UWFFmpOBq0JpdsySukE1FrEN5bUpoK8Z29fY=`.

And even the piece of code mentioned in my first issue comment:
```java
		Origin origin = URI.parse("http://localhost");
		Policy policy = new Policy(origin);
		policy.addDirective(new ScriptSrcDirective(Collections.singleton(new HashSource(HashSource.HashAlgorithm.SHA256, new Base64Value(Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest("doSubmit()".getBytes())))))));
		System.out.println(policy.show());
```

Weird, I cannot reproduce the initial behavior any longer that was misleading me and made me think SHA-256 hashes have to be of length 64. SHA-256 hashes are of course 32 bits, the hexadecimal representation is 64 characters... :confused: 

I think this issue may be closed and the PR be discarded. I'm so sorry having blamed you.

**Comment by cnsgithub** [comment]
@michaelficarra Oops, just realized you merged the PR. Are you sure? I think it has to be reverted, sorry.

**Comment by michaelficarra** [comment]
Oh no, that's not good. I'll let @shekyan take care of reverting it. At least it didn't go out in a release.

**Comment by cnsgithub** [comment]
You may add the invalid label...
