### ISSUE TITLE
Incorrect behavior when merging policies that don't contain fetch directives

### ISSUE THREAD

**Issue by shekyan** [shapesecurity/salvation#210]
Merging empty policy with `script-src a` should produce empty policy ` `.

Similarly, merging `frame-ancestors a` with `script-src a` should produce `frame-ancestors a`, 
as policy that does not contain fetch directives yields `script-src` to be not governed by CSP at all, rather than yielding `script-src *`.

**Comment by cnsgithub** [comment]
@shekyan Just noticed failing unit tests after upgrading to salvation 2.6.0.

Testing union merge of these headers:
- default-src 'none'
- script-src 'self'; img-src 'self'
- frame-ancestors https://foo.bar

**Salvation 2.5.0 - unit test passes:**
_expected = actual:_ `frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self';`

**Salvation 2.6.0 - unit test fails:**
_expected:_ `frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self';`
_actual:_ `frame-ancestors https://foo.bar;`

So the question is, which version behaves right?

**Comment by cnsgithub** [comment]
@shekyan Thanks for your answer. Ok, I see that it depends on the order of executing the particular union merge operations.

My unit test:
```java
Policy x = Parser.parse("frame-ancestors https://foo.bar", "http://example.com");
Policy y = Parser.parse("default-src 'none'", "http://example.com");
Policy z = Parser.parse("script-src 'self'; img-src 'self'", "http://example.com");
x.union(y);
x.union(z);
assertEquals("default-src; script-src 'self'; img-src 'self'; frame-ancestors https://foo.bar", x.show());
```

**Salvation 2.5.0 - unit test passes:**
```
Expected :frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'
Actual   :frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'
```

**Salvation 2.6.0 - unit test fails:**
```
Expected :frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'
Actual   :frame-ancestors https://foo.bar
```

While in salvation 2.5.0 merge operation seems to be associative, it seems not to be in 2.6.0.

**Salvation 2.5.0:**
`(x ∪ y) ∪ z = x ∪ (y ∪ z)
`

**Salvation 2.6.0:**
`(x ∪ y) ∪ z ≠ x ∪ (y ∪ z)
`

**Comment by cnsgithub** [comment]
Issue: https://github.com/shapesecurity/salvation/issues/213
