### ISSUE TITLE
2.7.1 vs 2.7.0 what's the scoop?

### ISSUE THREAD

**Issue by kingthorin** [shapesecurity/salvation#227]
The [releases content](https://github.com/shapesecurity/salvation/releases) doesn't seem to cover what was added/changed/fixed?

**Comment by kingthorin** [comment]
Hmmm I think I found it in the closed PRs, thought I guess there could have been a direct push to master by an admin that I don't see or something. But I guess it was mainly the worker-src fallback that was changed.

If I'm right just go ahead and close this ticket.

**Comment by michaelficarra** [comment]
All of the releases are tagged, so you can compare them yourself using GitHub's comparison feature: https://github.com/shapesecurity/salvation/compare/v2.7.0...v2.7.1

**Comment by bakkot** [comment]
Ah, yeah, I pushed a tag directly instead of using Github's "release" feature, sorry.

**Comment by michaelficarra** [comment]
@bakkot GitHub allows you to "release" an existing tag, so I've gone ahead and done that. Now it is labelled as the most recent release.
