### ISSUE TITLE
invalid policy Expecting directive-name but found " ".

### ISSUE THREAD

**Issue by AMANDUA** [shapesecurity/salvation#236]
![image](https://user-images.githubusercontent.com/17237753/80801197-3a3d3a80-8bc9-11ea-872c-c383ddca89f3.png)

What is the issue with the policy, can someone help??
Test report on `cspvalidator.org`

@shekyan  @benvinegar  @michaelficarra @LewisJEllis

**Comment by bakkot** [comment]
Sorry, this is a [bug](https://github.com/shapesecurity/salvation/issues/234) that has a [fix](https://github.com/shapesecurity/salvation/pull/235) which has not yet been released. I'll try to get on that.

**Comment by AMANDUA** [comment]
Thanks @bakkot

**Comment by bakkot** [comment]
This has been fixed and the fix released in 2.7.2.

**Comment by bakkot** [comment]
(cspvalidator.org still [needs to be updated](https://github.com/shapesecurity/salvation/issues/229) though.)
