### ISSUE TITLE
allow secure variant of scheme when only insecure is given

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/salvation#91]
See recent spec change here: https://github.com/w3c/webappsec-csp/issues/25#event-448827951

**Comment by shekyan** [comment]
Actually, this is going to be CSP3 feature. We have an option to either branch, or have the same code base for all versions with upper version indicator..

**Comment by michaelficarra** [comment]
I think we should just track the most recent version, as is done with most tooling for web features.

**Comment by shekyan** [comment]
Then we also need to support directives that exist in most recent version.

**Comment by shekyan** [comment]
6.1.10.3, 3, 2: If expression does not have a scheme-part ... changes the assumption that missing scheme in `source-expression` is http. 
there are more changes from level 2. 
We definitely need to discuss how to combine level 3 with what we already have.

**Comment by shekyan** [comment]
example: 
```
Policy p = Parser.parse("script-src a;", "http://example.com");
p.allowsScriptFromSource(Uri.parse("https://a")); // should be true, currently false
```
